/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.ArrayList;
import java.util.List;

public class PrimeFactors {

    public List<Integer> of(int number) {
        List<Integer> primeFactors = new ArrayList<>();
        return primeFactors;
    }
}
